export {default as Login } from "./Login"
export {default as Signup } from "./Signup"
export {default as Student } from "./Student"
export {default as Teacher } from "./Teacher"
export {default as Admin } from "./Admin"